
title: Curiosity is bliss
description:         Julien Couvreur's programming blog and more
tagline:             Julien Couvreur's programming blog and more
url:                 http://blog.monstuff.com
baseurl:             http://blog.monstuff.com
paginate:            3
author_name:         Julien Couvreur
ga:                  UA-74363-1
permalink:           /archives/:year/:month/:title.html
disqus_shortname:    curiosityisbliss

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
      comments: True
  -
    scope:
      path: "archives" 
    values:
      layout: "post"
      comments: True

prose:
  media: "archives/images"
  rooturl: '_posts'
  relativeLinks: 'http://blog.monstuff.com/links.jsonp'
  siteurl: 'http://blog.monstuff.com/'

sass:
  sass_dir:          _sass
  style:            :compressed

pages_list:       { 'Archive':'/archives.html', 'Feed':'/index.xml', 'About':'/about.html', 'Search':'https://cse.google.com/cse/publicurl?cx=005101733046013339255:zbcros0nd_0' }

exclude:
  - .gitignore
  - README.md

gems:
  - jekyll-redirect-from

encoding: UTF-8

timezone: America/Los_Angeles
