
title: Curiosity is bliss
description:         Julien Couvreur's programming blog and more
tagline:             Julien Couvreur's programming blog and more
url:                 http://blog2.monstuff.com
baseurl:             http://blog2.monstuff.com
paginate:            3
author_name:         Julien Couvreur
ga:                  UA-74363-1
permalink:           /archives/:year/:month/:title.html
disqus_shortname:    curiosityisbliss

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
      comments: True

prose:
  media: "archives/images"
  rooturl: '_posts'
  relativeLinks: 'http://blog2.monstuff.com/links.jsonp'
  siteurl: 'http://blog2.monstuff.com/'

sass:
  sass_dir:          _sass
  style:            :compressed

pages_list:       { 'Archive':'/archives.html', 'Feed':'/index.xml', 'About':'/about.html' }

exclude:
  - .gitignore
  - README.md

gems:
  - jekyll-redirect-from