
title: Curiosity is bliss
description:         Julien Couvreur's programming blog and more
tagline:             Julien Couvreur's programming blog and more
url:                 http://blog2.monstuff.com
paginate:            1
author_name:         Julien Couvreur
ga:                  UA-74363-1
permalink:           /archives/:year/:month/:title.html
disqus_shortname:    curiosityisbliss

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "post"
      comments: True

sass:
  sass_dir:          _sass
  style:            :compressed
